# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('copperRatio', models.FloatField()),
                ('yuanbaoRatio', models.FloatField()),
            ],
            options={
                'db_table': 'goldPrice',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=64)),
                ('skillPrice', models.FloatField()),
                ('roleId', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
    ]
